version: "3.8"
services:
  webapi-python:
    container_name: webapi-python
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=3.8

    command: /bin/sh -c "while sleep 1000; do :; done" 
    
    volumes:
      - ..:/workspace:cached