server:
  port: 8082
  servlet:
    context-path: /webapi

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/localdb
    username: admin
    password: admin
    hikari:
      connectionTimeout: 20000
      idleTimeout: 30000
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle: 2
      connectionTestQuery: SELECT 1
      #allow-pool-suspension: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_entity_auditing: true
        temp:
          use_jdbc_metadata_defaults: false

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/webapi.dev/protocol/openid-connect/certs

keycloak:
  policy-enforcer:
    realm: webapi.dev
    auth-server-url: http://keycloak:8080
    resource: webapibe
    credentials:
      secret: 9M2pfwj0qOp6EBaQgA5eSMYZWKCv3uEz
    http-method-as-scope: true


logging:
  level:
    org:
      springframework:
        security: DEBUG