server:
    port: 8081
    servlet:
        context-path: /webapi

spring:
    security:
        oauth2:
            resource-server:
                jwt:
                    issuer-uri: http://keycloak:8080/realms/webapi.dev
                    audience: webapibe
                    jwk-set-uri: http://keycloak:8080/realms/webapi.dev/protocol/openid-connect/certs
                    public-key: rsa


logging:
    level:
        org:
            springframework:
                security: DEBUG