ARG VARIANT=17-bullseye
FROM mcr.microsoft.com/devcontainers/java:${VARIANT}

#ARG GRADLE_VERSION=""
#RUN su vscode -c "umask 0002 && . /usr/local/sdkman/bin/sdkman-init.sh && sdk install gradle \"${GRADLE_VERSION}\""