version: '3'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=17-bullseye
    
    command: /bin/sh -c "while sleep 1000; do :; done" 

    volumes:
      - ..:/workspace:cached
      - ${GRADLE_HOME}:/home/vscode/.gradle:cached

    extra_hosts:
      - "database:192.168.1.16"
